// Makes tiny thumbnails of every mission image for the Missions list, so the page never has to
// fetch the originals (about 500 KB each). Run again when new missions appear:
//
//   node scripts/mission-thumbs.mjs
//
// Reads the missions table, fetches each image (AtomicHub's resizer first, the IPFS gateways as a
// fallback), writes public/img/missions/<cid>.webp at 160 px wide and src/data/missionThumbs.ts
// listing the CIDs that have one. Existing thumbnails are kept unless --force is given.
import { mkdirSync, existsSync, writeFileSync, readdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = resolve(root, 'public/img/missions')
const listFile = resolve(root, 'src/data/missionThumbs.ts')
const WIDTH = 160
const force = process.argv.includes('--force')

const RPC = ['https://wax.greymass.com', 'https://wax.eosusa.io', 'https://api.waxsweden.org']
const SOURCES = (cid) => [
  `https://resizer.atomichub.io/images/v1/preview?ipfs=${encodeURIComponent(cid)}&size=370`,
  `https://ipfs.alienworlds.io/ipfs/${cid}`,
  `https://ipfs.filebase.io/ipfs/${cid}`,
  `https://gateway.pinata.cloud/ipfs/${cid}`
]

async function missions() {
  for (const rpc of RPC) {
    try {
      const res = await fetch(`${rpc}/v1/chain/get_table_rows`, {
        method: 'POST',
        body: JSON.stringify({ json: true, code: 'miss.pdef', scope: 'miss.pdef', table: 'missions', limit: 500 })
      })
      const j = await res.json()
      if (j.rows) return j.rows
    } catch {
      // next node
    }
  }
  throw new Error('could not read the missions table')
}

async function fetchImage(cid) {
  for (const url of SOURCES(cid)) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(30_000) })
      if (!res.ok) continue
      const buf = Buffer.from(await res.arrayBuffer())
      if (buf.length < 100) continue
      return buf
    } catch {
      // next source
    }
  }
  return null
}

mkdirSync(outDir, { recursive: true })
const rows = await missions()
const cids = [
  ...new Set(rows.map((r) => String(JSON.parse(r.meta || '{}').image || '').replace(/^ipfs:\/\//, '')).filter(Boolean))
]
let made = 0
for (const cid of cids) {
  const file = resolve(outDir, `${cid}.webp`)
  if (existsSync(file) && !force) continue
  const buf = await fetchImage(cid)
  if (!buf) {
    console.warn('no image for', cid)
    continue
  }
  await sharp(buf).resize({ width: WIDTH, withoutEnlargement: true }).webp({ quality: 72 }).toFile(file)
  made++
  console.log('made', cid)
}
const have = readdirSync(outDir)
  .filter((f) => f.endsWith('.webp'))
  .map((f) => f.slice(0, -5))
  .sort()
writeFileSync(
  listFile,
  `// Generated by scripts/mission-thumbs.mjs: mission image CIDs that have a thumbnail in public/img/missions/.\nexport const MISSION_THUMBS = new Set<string>(${JSON.stringify(have, null, 2)})\n`
)
console.log(`${made} new, ${have.length} thumbnails in all`)
